{{- if and .Values.singleuser.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: singleuser
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $_ := merge (dict "componentLabel" "singleuser-server") . }}
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # allowed pods (hub.jupyter.org/network-access-singleuser) --> singleuser-server
    - ports:
        - port: notebook-port
      from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-singleuser: "true"

    {{- with .Values.singleuser.networkPolicy.ingress }}
    # default: nothing --> singleuser-server
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}

  egress:
    # singleuser-server --> hub
    - ports:
        - port: 8081
      to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "hub") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}

    # singleuser-server -> Kubernetes internal DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    {{- with .Values.singleuser.networkPolicy.egress }}
    # singleuser-server --> default: everything
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
{{- end }}
