destination: &ci_cd_ns labs-ci-cd

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

applications:
  # tekton nodejs demo pipeline using a strict implementation of gitflow on github
  - name: tekton-github-nodejs
    enabled: true
    source: https://github.com/mvmaestri/helm-charts.git
    source_path: charts/tekton-demo
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    source_ref: develop
    values:
      cluster: apps.s45.core.rht-labs.com
      application:
        name: do101
        runtime: nodejs:10
        environments:
          cicd: *ci_cd_ns
          development: do101-development
          production: do101-production
      pipeline:
        name: nodejs
        sa:
          default: pipeline
          triggers: tekton-triggers-sa
        nexus:
          host: https://nexus-labs-ci-cd.apps.s45.core.rht-labs.com/repository/labs-npm
        build:
          s2i:
            context: weather
        webhook:
          github: 
            org: mvmaestri
            user: mvmaestri
            repo: do101-apps
            secret: github-webhook-secret
            key: github-deploy-secret