destination: &ci_cd_ns labs-ci-cd

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

applications:
  - name: tekton-treo
    enabled: true
    source: https://github.com/mvmaestri/helm-charts.git
    source_path: charts/tekton-demo
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    source_ref: feature/multiple-instances
    values:
      cluster: apps.s45.core.rht-labs.com
      application:
        name: treo
        runtime: nodejs:10
        environments:
          cicd: labs-ci-cd
          development: treo-development
          production: treo-production
      pipeline:
        sa:
          default: pipeline
          triggers: treo-tekton-triggers-sa
        nexus:
          host: https://nexus-labs-ci-cd.apps.s45.core.rht-labs.com/repository/labs-npm
        build:
          s2i:
            context: .
        webhook:
          github: 
            org: mvmaestri
            user: mvmaestri
            repo: treo
            secret: treo-github-webhook-secret
            key: treo-github-deploy-secret