{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $autoHTTPS := and $HTTPS (and (eq .Values.proxy.https.type "letsencrypt") .Values.proxy.https.hosts) -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- if .Values.proxy.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # allowed pods (hub.jupyter.org/network-access-proxy-http) --> proxy (http/https port)
    - ports:
        - port: http
        {{- if or $manualHTTPS $manualHTTPSwithsecret }}
        - port: https
        {{- end }}
      from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-http: "true"

    # allowed pods (hub.jupyter.org/network-access-proxy-api) --> proxy (api port)
    - ports:
        - port: api
      from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-api: "true"

    {{- with .Values.proxy.networkPolicy.ingress}}
    # default: nothing --> proxy
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}

  egress:
    # proxy --> hub
    - ports:
        - port: 8081
      to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "hub") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}

    # proxy --> singleuser-server
    - ports:
        - port: 8888
      to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "singleuser-server") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}

    # proxy -> Kubernetes internal DNS
    - ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53

    {{- with .Values.proxy.networkPolicy.egress }}
    # proxy --> default: everything
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
{{- end }}
